Filter teams based on user ou
BeSaRa/customs pull request #271
Opened 2024-03-26 12:08 UTC by weradsaoud

2024-03-26 13:21 UTC, aalshahin requested changes
this changes is needed for approving

2024-03-27 10:18 UTC, weradsaoud commented on src/modules/administration/popups/internal-user-ou-popup/internal-user-ou-popup.component.ts
> +        console.log('this.organizationUnits: ', this.organizationUnits);
done

2024-03-27 10:18 UTC, weradsaoud commented on src/modules/administration/popups/internal-user-ou-popup/internal-user-ou-popup.component.ts
> +            o.type === OrganizationUnitType.ADMINISTRATION,
done

2024-03-27 10:20 UTC, weradsaoud commented on src/modules/administration/popups/organization-unit-popup/organization-unit-popup.component.ts
> +          console.log('internalUsers', internalUsers);
done

2024-03-27 10:24 UTC, weradsaoud commented on src/modules/administration/popups/internal-user-ou-popup/internal-user-ou-popup.component.html
> +            [options]="departmentUnits"
done

2024-03-27 10:37 UTC, closed without merging